### ISSUE TITLE
GHC 8.0.1 warning

### ISSUE THREAD

**Issue by asr** [jonaprieto/tstp2agda#10]
I'm getting this warning using GHC 8.0.1:

```
-XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
```

**Comment by jonaprieto** [comment]
I didn't reproduce this warning with `cabal install` with this same version of ghc. Some reason?

**Comment by asr** [comment]
Neither do I.
