### ISSUE TITLE
No arguments

### ISSUE THREAD

**Issue by asr** [jonaprieto/tstp2agda#17]
Running tstp2agda without arguments I got

```
$ tstp2agda 

-- | tstp2agda proof

open import Data.FOL.Shallow
open import Function using (id)
```

and the command is waiting some input.

**Comment by jonaprieto** [comment]
That's because is working with the standard input, I can remove that feature or I can print it out after finish the reading of the sdtin. What do you think?

**Comment by asr** [comment]
Remove the feature please.
