### ISSUE TITLE
Agda error using the deep embedding

### ISSUE THREAD

**Issue by asr** [jonaprieto/tstp2agda#19]
In our last meeting, you show me an Agda error using the deep embedding. Could you give me instructions for reproducing this error, please.

**Comment by jonaprieto** [comment]
was about filling the hole?

**Comment by asr** [comment]
Yes.

**Comment by jonaprieto** [comment]
Go to src/Data/FOL/Deep and inside the Theorems.agda file,  try splitting `x` in the following function:

```Agda
Foo : Prop -> Prop
Foo x = ?
```

**Comment by asr** [comment]
This is a known issue. See https://github.com/agda/agda/issues/2245.
